arguments:
  format: json
git_services:
- host: github.com
  repos:
  - redhat-appstudio/o11y
  - redhat-appstudio/book
  - redhat-appstudio/build-definitions
  - redhat-appstudio/e2e-tests
  - redhat-appstudio/infra-deployments
  #- renovatebot/renovate
  - tektoncd/chains
  token: "${GITHUB_TOKEN}"
  type: github
