arguments:
  format: json
git_services:
- host: github.com
  repos:
  - redhat-appstudio/o11y
  - redhat-appstudio/book
  - redhat-appstudio/e2e-tests
  - redhat-appstudio/infra-deployments
  - redhat-appstudio/segment-bridge
  #- renovatebot/renovate
  token: "${GITHUB_TOKEN}"
  type: github
